import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    yetAnotherCobblestoneGenerator: [
        {
            type: 'autogenerated',
            dirName: 'yet-another-cobblestone-generator'
        }
    ],
    deathCounter: [
        {
            type: 'autogenerated',
            dirName: 'death-counter'
        }
    ],
    duckyUpdaterReWork: [
        {
            type: 'autogenerated',
            dirName: 'ducky-updater-rework'
        }
    ],
    modMenuBadgesLib: [
        {
            type: 'autogenerated',
            dirName: 'modmenu-badges-lib'
        }
    ],
    duckyUpdaterLib: [
        {
            type: 'autogenerated',
            dirName: 'ducky-updater-lib'
        }
    ],
};

export default sidebars;
