import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    yetAnotherCobblestoneGenerator: [
        {
            type: 'autogenerated',
            dirName: 'mods/yet-another-cobblestone-generator',
        }
    ],
    deathCounter: [
        {
            type: 'autogenerated',
            dirName: 'mods/death-counter'
        }
    ],
    duckyUpdaterReWork: [
        {
            type: 'autogenerated',
            dirName: 'mods/ducky-updater-rework'
        }
    ],
    modMenuBadgesLib: [
        {
            type: 'autogenerated',
            dirName: 'libs/modmenu-badges-lib'
        }
    ],
    duckyUpdaterLib: [
        {
            type: 'autogenerated',
            dirName: 'libs/ducky-updater-lib'
        }
    ],
};

export default sidebars;
